# Generated by Django 3.2.8 on 2021-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_monthlyprecipitation_seasonalprecipitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growing_period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='water_needed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
