# Generated by Django 3.2.8 on 2021-11-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_auto_20211112_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
