# Generated by Django 3.2.8 on 2021-11-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_extensionworker_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('status_code', models.IntegerField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
