COUNTRY_CHOICES = (
    ("Nigeria", "Nigeria"),
    ("Ethiopia", "Ethiopia"),
    ("Egypt", "Egypt"),
    ("DR Congo", "DR Congo"),
    ("Tanzania", "Tanzania"),
    ("South Africa", "South Africa"),
    ("Kenya", "Kenya"),
    ("Uganda", "Uganda"),
    ("Sudan", "Sudan"),
    ("Algeria", "Algeria"),
    ("Morocco", "Morocco"),
    ("Angola", "Angola"),
    ("Ghana", "Ghana"),
    ("Mozambique", "Mozambique"),
    ("Madagascar", "Madagascar"),
    ("Ivory Coast", "Ivory Coast"),
    ("Cameroon", "Cameroon"),
    ("Niger", "Niger"),
    ("Mali", "Mali"),
    ("Burkina Faso", "Burkina Faso"),
    ("Malawi", "Malawi"),
    ("Zambia", "Zambia"),
    ("Chad", "Chad"),
    ("Somalia", "Somalia"),
    ("Senegal", "Senegal"),
    ("Zimbabwe", "Zimbabwe"),
    ("Guinea", "Guinea"),
    ("Rwanda", "Rwanda"),
    ("Benin", "Benin"),
    ("Burundi", "Burundi"),
    ("Tunisia", "Tunisia"),
    ("South Sudan", "South Sudan"),
    ("Togo", "Togo"),
    ("Sierra Leone", "Sierra Leone"),
    ("Libya", "Libya"),
    ("Republic of the Congo", "Republic of the Congo"),
    ("Central African Republic", "Central African Republic"),
    ("Liberia", "Liberia"),
    ("Mauritania", "Mauritania"),
    ("Eritrea", "Eritrea"),
    ("Gambia", "Gambia"),
    ("Botswana", "Botswana"),
    ("Namibia", "Namibia"),
    ("Gabon", "Gabon"),
    ("Lesotho", "Lesotho"),
    ("Guinea-Bissau", "Guinea-Bissau"),
    ("Equatorial Guinea", "Equatorial Guinea"),
    ("Mauritius", "Mauritius"),
    ("Eswatini", "Eswatini"),
    ("Djibouti", "Djibouti"),
    ("Comoros", "Comoros"),
    ("Cape Verde", "Cape Verde"),
    ("Sao Tome and Principe", "Sao Tome and Principe"),
    ("Seychelles", "Seychelles"),
)
